esphome:
  name: acindicator
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "salmona"
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

switch:
  - platform: gpio
    pin: D0
    name: "Naomi A/C indicator"
  - platform: gpio
    pin: D2
    name: "Ofra A/C indicator"

